apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: eyndrahena/booking-service:latest
          env:
            - name: CatalogServiceRpcEndpoint
              valueFrom:
                configMapKeyRef:
                  name: booking-service-cm
                  key: catalog-service-rpc-endpoint

---

apiVersion: v1
kind: Service
metadata:
  name: booking-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
    - name: booking-service
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: booking-service-np
spec:
  type: NodePort
  selector:
    app: booking-service
  ports:
    - name: booking-service
      protocol: TCP
      port: 80
      targetPort: 80
