apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    kubernetes.io/ingress.class: nginx
    ngingx.ingress.io/use-regex: 'true'
spec:
  rules:
    - host: acme.com
      http:
        paths:
          - path: /api/m
            pathType: Prefix
            backend:
              service:
                name: data-mng-service-clusterip
                port:
                  number: 80
          - path: /api/c
            pathType: Prefix
            backend:
              service:
                name: flight-catalog-service-clusterip
                port:
                  number: 80
