apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
        - name: management
          image: eyndrahena/management:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: management-cm
                  key: database-host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: management-cm
                  key: database-port
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: management-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: management-db-credentials
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: management-cip
spec:
  type: ClusterIP
  selector:
    app: management
  ports:
    - name: management
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: management-np
spec:
  type: NodePort
  selector:
    app: management
  ports:
    - name: management
      protocol: TCP
      port: 80
      targetPort: 80
