apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-db-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-db-deploy
  labels:
    app: catalog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
        - name: catalog-db
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "catalog-db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: catalog-db-credentials
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: catalog-db-credentials
          volumeMounts:
            - mountPath: /var/opt/db/catalog-db/data
              name: catalog-db
      volumes:
        - name: catalog-db
          persistentVolumeClaim:
            claimName: catalog-db-claim

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-db-cip
spec:
  type: ClusterIP
  selector:
    app: catalog-db
  ports:
    - name: catalog-db
      protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-db
spec:
  ports:
    - port: 10002
      protocol: TCP
      targetPort: 5432
  selector:
    app: catalog-db
  type: LoadBalancer
