apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: eyndrahena/catalog:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: catalog-cm
                  key: database-host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: catalog-cm
                  key: database-port
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: catalog-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-db-credentials
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-cip
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - name: catalog
      protocol: TCP
      port: 80
      targetPort: 80
    - name: catalog-grpc
      protocol: TCP
      port: 666
      targetPort: 666

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-np
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
    - name: catalog
      protocol: TCP
      port: 80
      targetPort: 80
