apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: eyndrahena/catalog:latest
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-db-sa-pass
                  key: SA_PASSWORD
            - name: MSSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: catalog-cm
                  key: database-url

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-cip
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - name: catalog
      protocol: TCP
      port: 80
      targetPort: 80
    - name: catalog-grpc
      protocol: TCP
      port: 666
      targetPort: 666

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-np
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
    - name: catalog
      protocol: TCP
      port: 80
      targetPort: 80
