apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: eyndrahena/booking:latest
          env:
            - name: CatalogRpcEndpoint
              valueFrom:
                configMapKeyRef:
                  name: booking-cm
                  key: catalog-rpc-endpoint

---

apiVersion: v1
kind: Service
metadata:
  name: booking-cip
spec:
  type: ClusterIP
  selector:
    app: booking
  ports:
    - name: booking
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: booking-np
spec:
  type: NodePort
  selector:
    app: booking
  ports:
    - name: booking
      protocol: TCP
      port: 80
      targetPort: 80
